# NumPy Taller



# Sebastian Samaniego
# Cod. 506231082

#### Importar NumPy como np

In [68]:
import numpy as np

#### Crear un arreglo de 10 ceros

In [69]:
arreglo_de_ceros = np.zeros(10)
print(arreglo_de_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [70]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

#### Crear un arreglo de 10 unos

In [71]:
arreglo_de_unos = np.ones(10)
print(arreglo_de_unos)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [72]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

#### Crear un arreglo de 10 cincos

In [73]:
arreglo_de_cincos = np.array([5.0] * 10)
print(arreglo_de_cincos)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [74]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

#### Crear un arreglo de los números enteros desde 10 hasta 50 (incluido)

In [75]:
arreglo_enteros = np.arange(10, 51)
print(arreglo_enteros)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [76]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

#### Crear un arreglo de todos los números pares entre 10 y 50 (incluido)

In [77]:
arreglo_pares = np.arange(10, 51, 2)
print(arreglo_pares)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [78]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

#### Crear una matriz de 3x3 con valores desde 0 a 8

In [79]:
matriz3x3 = np.arange(9).reshape(3, 3)
print(matriz3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [80]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

#### Crear una matriz identidad de 3x3

In [81]:
matriz_identidad = np.identity(3)
print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [82]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

#### Usar NumPy para generar un número aleatorio entre 0 y 1

In [83]:
numero_aleatorio = np.random.rand()
print(numero_aleatorio)

0.5566048417575113


In [84]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO
# Su resultado será diferente

#### Usar NumPy para generar 25 números aleatorios con una distribución de probabilidad normal

In [85]:
numeros_aleatorios_normales = np.random.normal(size=25)
print(numeros_aleatorios_normales)

[ 1.32307334  0.92884156 -1.95132828  0.4759484  -0.69422781 -0.89689269
  1.33349114  2.41225886 -0.10651325  0.25044704 -1.67925004 -1.4679374
 -1.93916159 -0.50635672 -0.28850138 -1.08937701  0.85927409  0.14960926
  1.14232812 -0.62053109  0.54148536  0.33813974  0.63959346 -0.48014508
  0.01293102]


In [86]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO
# Su resultado será diferente

#### Crear la siguiente matriz:

In [87]:
matrizdeci = np.arange(0.01, 1.01, 0.01)
print(matrizdeci)

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.  ]


In [88]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

#### Crear un arreglo de 20 elementos linealmente separados entre 0 y 1:

In [89]:
arreglo_lineal = np.linspace(0, 1, 20)
print(arreglo_lineal)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [90]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

## Numpy - Índices y Selección

A partir de la siguiente matriz, replique los resultados que se presentan a continuación:

In [91]:
matriz_original = np.array([[ 1,  2,  3,  4,  5],
                            [ 6,  7,  8,  9, 10],
                            [11, 12, 13, 14, 15],
                            [16, 17, 18, 19, 20],
                            [21, 22, 23, 24, 25]])
print(matriz_original)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [92]:
# ESCRIBA SU CODIGO AQUI PARA NO BORRAR EL RESULTADO ESPERADO
submatriz = matriz_original[2:5, 1:5]
print(submatriz)


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [93]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

In [94]:
# ESCRIBA SU CODIGO AQUI PARA NO BORRAR EL RESULTADO ESPERADO
valor = matriz_original[3, 4]
print(valor)

20


In [95]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

In [96]:
# ESCRIBA SU CODIGO AQUI PARA NO BORRAR EL RESULTADO ESPERADO
matriz_deseada = matriz_original[0:3, 1:2]
print(matriz_deseada)

[[ 2]
 [ 7]
 [12]]


In [97]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

In [98]:
# ESCRIBA SU CODIGO AQUI PARA NO BORRAR EL RESULTADO ESPERADO
matriz_deseada2 = matriz_original[4:5, 0:5]
print(matriz_deseada2)


[[21 22 23 24 25]]


In [99]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

In [100]:
# ESCRIBA SU CODIGO AQUI PARA NO BORRAR EL RESULTADO ESPERADO
matriz_deseada3 = matriz_original[3:5, 0:5]
print(matriz_deseada3)


[[16 17 18 19 20]
 [21 22 23 24 25]]


In [101]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

## NumPy - Operaciones

In [102]:
mat = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Obtener la suma de todos los valores de la matriz 'mat'

In [103]:
suma_total = np.sum(mat)
print(suma_total)

325


In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

325

#### Obtener las desviación estándar de los valores en la matriz 'mat'

In [105]:
desviacion_estandar = np.std(mat)
print(desviacion_estandar)

7.211102550927978


In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

7.211102550927978

#### Obtener la suma de los valores en cada columna de la matriz

In [106]:
suma_columnas = np.sum(mat, axis=0)
print(suma_columnas)


[55 60 65 70 75]


In [ ]:
# NO USAR ESTA CELDA PARA QUE NO SE BORRE EL RESULTADO ESPERADO

array([55, 60, 65, 70, 75])